
-- Easybox SQL Schema
-- NOTE: This schema includes exclusion constraints commented out for optional manual use with PostGIS enabled.

CREATE TABLE easybox (
                         id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         address    VARCHAR(255),
                         latitude   DOUBLE PRECISION NOT NULL,
                         longitude  DOUBLE PRECISION NOT NULL,
                         status     VARCHAR(255),
                         device_url VARCHAR(255),
                         version    BIGINT DEFAULT 0
);

CREATE TABLE bakery (
                        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name             VARCHAR(255),
                        phone            VARCHAR(255),
                        plugin_installed BOOLEAN
);

CREATE TABLE compartment (
                             id          SERIAL PRIMARY KEY,
                             easybox_id  BIGINT NOT NULL REFERENCES easybox(id),
                             size        INTEGER NOT NULL,
                             temperature INTEGER NOT NULL,
                             status      VARCHAR(50) NOT NULL,
                             condition   VARCHAR(50) NOT NULL,
                             version     BIGINT
);

CREATE TABLE users (
                       id           BIGSERIAL PRIMARY KEY,
                       name         VARCHAR(120),
                       phone_number VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE reservation (
                             id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             client            VARCHAR(255),
                             delivery_time     TIMESTAMP(6),
                             status            VARCHAR(255),
                             easybox_id        BIGINT REFERENCES easybox(id),
                             reservation_start TIMESTAMP,
                             reservation_end   TIMESTAMP,
                             compartment_id    BIGINT NOT NULL,
                             user_id           BIGINT,
                             version           BIGINT,
                             expires_at        TIMESTAMP,
                             bakery_id         BIGINT REFERENCES bakery(id)
);

CREATE INDEX idx_reservation_expiry ON reservation (status, expires_at);

